channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.15.1
  - cloudpickle==2.2.1
  - google-api-core==2.12.0
  - numpy==1.24.3
  - tensorflow-intel==2.14.0
  - tensorflow==2.14.0
name: mlflow-env
